# Generated by Django 2.0.4 on 2018-04-21 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=5000)),
                ('numOfStudents', models.CharField(max_length=3)),
                ('oldPrice', models.CharField(max_length=5)),
                ('newPrice', models.CharField(max_length=5)),
            ],
        ),
    ]
